Repository Team26SWP/InnoAlias, pull requests merged in 2025-07, with the labels that each got.

#120 Fix #109
  backend/app/routers/game.py
  backend/app/services/game_service.py
Labels: bugfix

#154 added git workflow and secrets management to the README
  .github/PULL_REQUEST_TEMPLATE/pull_request_template.md
  README.md
Labels: documentation

#159 build&deployment section complete
  README.md
  docs/architecture/deployment-view/deployment-guide.md
  docs/architecture/filler.txt
  docs/backend/README.md
  docs/backend/index.html
Labels: documentation

#165 Added admin panel
  .idea/workspace.xml
  backend/app/main.py
  backend/app/models/__init__.py
  backend/app/routers/admin_panel.py
Labels: enhancement

#186 new docs
  backend/app/models/__init__.py
  backend/app/services/aigame_service.py
  docs/backend/README.md
  docs/backend/index.html
Labels: documentation

#221 added new system prompt and context awareness
  backend/app/config.py
  backend/app/services/aigame_service.py
Labels: enhancement, bugfix

#222 adding a link to the gallery via arrows to the home page
  frontend/src/components/Home.tsx
Labels: enhancement

#225 Add backend documentation comments
  backend/app/code_gen.py
  backend/app/db.py
  backend/app/routers/game.py
  backend/app/services/game_service.py
Labels: codex

#230 Fix mypy errors
  backend/app/routers/game.py
  backend/app/services/game_service.py
Labels: codex

#231 Bugfixing backend
  .github/workflows/ci.yml
  backend/README.md
  backend/app/code_gen.py
  backend/app/db.py
  backend/app/main.py
  backend/app/models/__init__.py
  backend/app/routers/admin_panel.py
  backend/app/routers/aigame.py
  backend/app/routers/auth.py
  backend/app/routers/game.py
  backend/app/routers/profile.py
  backend/app/services/admin_service.py
  backend/app/services/aigame_service.py
  backend/app/services/auth_service.py
  backend/app/services/gallery_service.py
  backend/app/services/game_service.py
  backend/app/services/profile_service.py
  backend/tests/_test_setup.py
  backend/tests/conftest.py
  backend/tests/test_auth_integration.py
  backend/tests/test_auth_unit.py
  backend/tests/test_code_gen_unit.py
  backend/tests/test_game_service_unit.py
  backend/tests/test_integration.py
  backend/tests/test_new_unit_tests.py
  docs/API.md
  docs/architecture/dynamic-view/performance-test.py
  pyproject.toml
Labels: enhancement, bugfix

#233 Bugfix backend
  backend/app/config.py
  backend/app/models/__init__.py
  backend/app/routers/admin_panel.py
  backend/app/routers/gallery.py
  backend/app/routers/profile.py
  backend/app/services/admin_service.py
  backend/app/services/gallery_service.py
  backend/app/services/profile_service.py
  backend/tests/test_admin_panel_unit.py
  backend/tests/test_gallery_unit.py
  backend/tests/test_integration.py
  docs/API.md
  docs/architecture/dynamic-view/performance-test.py
Labels: documentation, enhancement, bugfix

#243 Bugfixing
  backend/app/routers/game.py
  backend/app/services/game_service.py
Labels: bugfix

#248 fix aigame
  backend/app/services/aigame_service.py
  backend/requirements.txt
Labels: bugfix

#249 Fix aigame
  backend/Dockerfile
  backend/requirements.txt
Labels: bugfix

#250 Privacy fix
  backend/app/services/profile_service.py
Labels: bugfix

#251 fix CI
  backend/app/services/aigame_service.py
Labels: bugfix
